server:
  port: 8989

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: order-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**


